# Generated by Django 2.1.7 on 2019-10-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='tagg',
            new_name='tag',
        ),
    ]
