# Generated by Django 2.1.7 on 2019-10-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20191006_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='tag',
            field=models.CharField(default='Others', max_length=50),
        ),
    ]
