# Generated by Django 2.0.1 on 2019-10-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20191023_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
