# Generated by Django 2.2.6 on 2019-10-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20191023_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='file',
            new_name='image',
        ),
    ]
